// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A flow to generate a blog post from a YouTube video transcript.
 *
 * - generateBlogFromTranscript - A function that generates a blog post from a YouTube video transcript.
 * - GenerateBlogFromTranscriptInput - The input type for the generateBlogFromTranscript function.
 * - GenerateBlogFromTranscriptOutput - The return type for the generateBlogFromTranscript function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateBlogFromTranscriptInputSchema = z.object({
  videoTranscript: z
    .string()
    .describe('The transcript of the YouTube video to generate a blog post from.'),
  blogTopic: z.string().describe('The topic of the blog post to generate.'),
});
export type GenerateBlogFromTranscriptInput = z.infer<
  typeof GenerateBlogFromTranscriptInputSchema
>;

const GenerateBlogFromTranscriptOutputSchema = z.object({
  blogPost: z.string().describe('The generated blog post.'),
});
export type GenerateBlogFromTranscriptOutput = z.infer<
  typeof GenerateBlogFromTranscriptOutputSchema
>;

export async function generateBlogFromTranscript(
  input: GenerateBlogFromTranscriptInput
): Promise<GenerateBlogFromTranscriptOutput> {
  return generateBlogFromTranscriptFlow(input);
}

const generateBlogFromTranscriptPrompt = ai.definePrompt({
  name: 'generateBlogFromTranscriptPrompt',
  input: {schema: GenerateBlogFromTranscriptInputSchema},
  output: {schema: GenerateBlogFromTranscriptOutputSchema},
  prompt: `You are an expert blog post writer.

You will generate a blog post from the transcript of a YouTube video.

The blog post should be on the topic of: {{{blogTopic}}}.

Use the following transcript as the source of information for the blog post:

{{{videoTranscript}}}
`,
});

const generateBlogFromTranscriptFlow = ai.defineFlow(
  {
    name: 'generateBlogFromTranscriptFlow',
    inputSchema: GenerateBlogFromTranscriptInputSchema,
    outputSchema: GenerateBlogFromTranscriptOutputSchema,
  },
  async input => {
    const {output} = await generateBlogFromTranscriptPrompt(input);
    return output!;
  }
);
